### PR TITLE
Increase sanity level of string handling

### LINKED ISSUE #23: __repr__ is broken on Python 3
As far as I can tell, the intention is that `_pem_str` is unicode on Python 3. But `__repr__` tries to pass it to `hashlib.sha1` which requires bytes, thus explosions.

### PR DESCRIPTION
**Pull request by mithrandi**
This PR makes the PEM objects always use `bytes` internally. In addition:
 - An `as_bytes` method is added for always getting `bytes`.
 - `__str__` still returns a native string as required by Python.
 - `__repr__` doesn't explode on Python 3 (fixes #23)
 - Constructing the PEM object types with either `unicode` or `bytes` now works on both Py 2/3, but the `unicode` path is deprecated.

### CODE REVIEW

**Comment by hynek** [comment]
Hm since PEM is about convenience, I'd say that deprecating Unicode construction is not desirable.

**Comment by mithrandi** [comment]
Hmm, I guess I don't really have strong feelings either way! Reverted the deprecation.

**Comment by mithrandi** [comment]
I have no idea what the heck that Travis failure is about, but I'm pretty sure it's not my fault :grin:

**Comment by hynek** [comment]
yeah it was just Travis being a distributed system

**Comment by hynek** [comment]
Code looks OK but you’ll have to fix the docs still.  Currently it says `They have *no public API* except that they can be transformed using ``str(obj)`` into a PEM string.` which is not patently wrong. :)

**Comment by mithrandi** [comment]
Okay, pushed a change, did I miss anything else that needs to be updated?

**Comment by hynek** [comment]
I think all that’s missing is a link to this PR and we’re done!

**Comment by mithrandi** [comment]
Ah, yes. Added :)

**Comment by hynek** [comment]
Thanks!

**Pull request merged**
