### PR TITLE
Add CRL support

### PR DESCRIPTION
**Pull request by RazerM**

### CODE REVIEW

**Comment by hynek** [comment]
Thanks!

**Comment by RazerM** [comment]
@hynek I don't want to make any demands of your time, but do you have a rough idea of when 18.2 will be released?

**Comment by hynek** [comment]
Not before October because I’m currently quite far from any kind of computer. :)

**Comment by hynek** [comment]
FYI 18.2 is out

**Comment by RazerM** [comment]
Thanks!

**Pull request merged**
