### PR TITLE
Add support for parsing certificate requests.

### PR DESCRIPTION
**Pull request by vpelletier**
Support both "old" (NEW CERTIFICATE REQUEST) and "normal"
(CERTIFICATE REQUEST) captions.

### CODE REVIEW

**Comment by vpelletier** [comment]
Test failure looks unrelated to this PR:
```
setup.py:44:1: E305 expected 2 blank lines after class or function definition, found 1
```

**Comment by hynek** [comment]
hi thanks for the PR, I’ve fixed the flake8 in master so you should be able to rebase.

The changes look straight-forward enough, but the new class  needs to be added to https://raw.githubusercontent.com/hynek/pem/master/docs/api.rst

thanks!

**Comment by vpelletier** [comment]
Thanks for pointing api.rst out, I missed it. I rebased & amended my commit.

**Comment by hynek** [comment]
Thanks!

**Comment by hynek** [comment]
FYI, since I have no real TODOs, I’ve release a 17.1 with just your change: https://pypi.org/project/pem/

**Comment by vpelletier** [comment]
Thanks for the releas ! Now my project only needs to wait for the next `cryptography` release and all dependencies will be available on pypi.

**Pull request merged**
